on:
    push:
        branches: main

env:
    IMAGE_NAME: ${{ github.repository }}

name: Deploy Docker image
jobs:
    build_and_push_to_registry:
        runs-on: ubuntu-latest
        permissions:
            packages: write
            contents: read
        steps:
            - name: Checkout
              uses: actions/checkout@v4
            - name: Login to GHCR
              uses: docker/login-action@v3
              with:
                username: ${{ secrets.DOCKERHUB_USERNAME }}
                password: ${{ secrets.DOCKERHUB_TOKEN }}
            - name: Install tools
              uses: docker/setup-buildx-action@v3
              id: buildx
              with:
                install: true
            - name: Build image
              run: docker build -t home-scripts .
            - name: Deploy
              uses: docker/build-push-action@v6
              with:
                push: true
                tags: home-scripts
